import {lessonThree,thirdWorksheet} from './lesson-three.js';
import {lessonTwo,teacherForm,worksheetFor,secondWorksheet} from './lesson-two.js';
import {lessonOne,lessonOneReport,observationIds,worksheetUrl} from './lesson-one.js';
import {artifacts,coreArtifacts,lessons,promises,textbook,themes,lessonVisuals} from './data.js';
import {STORAGE_KEY,fresh,escapeHtml as e,safeUrl,validateProject,wordCounts,selectedRecords,readiness} from './model.js';
let project=fresh(), storageError=false;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)project=validateProject(JSON.parse(raw));}catch{storageError=true;}
let lessonOneSource='susan',lessonOneExample=0;
let lessonTwoSource=observationIds.includes(project.answers['l2-selected-artifact'])?project.answers['l2-selected-artifact']:'house',lessonTwoReason=false;
let slide=0,reveal=false,mode='book',large=false,filter='전체',wordNation='전체',themeFilter='전체',showExtra=false;
let compareIds=(project.answers['compare-selected']||'').split(',').filter(id=>artifacts.some(a=>a.id===id)).slice(0,2);
const $=s=>document.querySelector(s);
const art=id=>artifacts.find(x=>x.id===id);
const answer=k=>project.answers[k]||'';
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(project));storageError=false;$('#save-status')&&( $('#save-status').textContent='이 기기에 저장됨');}catch{storageError=true;$('#save-status')&&($('#save-status').textContent='저장 공간 부족 · 작업 파일을 내려받으세요');}}
const comparisonKey=(kind,ids=compareIds)=>`compare-${[...ids].sort().join('__')}-${kind}`;
function migrateComparisonNotes(){
 if(compareIds.length!==2)return;
 let changed=false;
 for(const kind of ['common','different','evidence']){
  const legacy='compare-'+kind,key=comparisonKey(kind);
  if(Object.hasOwn(project.answers,legacy)){
   if(!Object.hasOwn(project.answers,key))project.answers[key]=project.answers[legacy];
   delete project.answers[legacy];changed=true;
  }
 }
 if(changed)save();
}
migrateComparisonNotes();
function toast(message){$('#toast').textContent=message;clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').textContent='',4200);}
const btn=(label,action,extra='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const link=(url,label)=>safeUrl(url)?`<a href="${e(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`:`<span>${e(label)}</span>`;
const field=(key,label,placeholder='',rows=3)=>`<label class="field"><span>${e(label)}</span><textarea data-answer="${e(key)}" rows="${rows}" maxlength="12000" placeholder="${e(placeholder)}">${e(answer(key))}</textarea></label>`;
const input=(key,label,placeholder='')=>`<label class="field"><span>${e(label)}</span><input data-answer="${e(key)}" maxlength="200" value="${e(answer(key))}" placeholder="${e(placeholder)}"></label>`;
const select=(key,label,options,value=answer(key))=>`<label class="field"><span>${e(label)}</span><select data-answer="${e(key)}">${options.map(x=>`<option ${value===x?'selected':''}>${e(x)}</option>`).join('')}</select></label>`;
const bookLabel=a=>a.core?`교과서 ${a.page}쪽`:'추가 탐구';
function photo(a,cls=''){
 if(!a.image)return `<figure class="artifact-photo source-study ${cls}"><div class="study-sheet"><span class="page-tag">${bookLabel(a)}</span><small>${e(a.nation)} · ${e(a.theme)}</small><h3>${e(a.name)}</h3><p>${e(a.observe)}</p><a class="button quiet" href="${e(textbook.url)}" target="textbook" rel="noopener">교과서 사진 보기 ↗</a><small>책을 펼친 뒤 ${a.page}쪽으로 이동하세요.</small></div></figure>`;
 return `<figure class="artifact-photo ${cls}"><img src="assets/images/${a.image}" alt="${e(a.name)}" loading="lazy"><figcaption>${e(a.name)}${a.imageNote?`<small class="image-note">${e(a.imageNote)}</small>`:''}<span>${link(a.creditUrl,a.credit)}${a.license?' · '+link(a.license,'이용 조건'):''}</span></figcaption></figure>`;
}
const bookContext=(id)=>`<div class="textbook-context"><span>${textbook.title}</span><span>${id===1?'25·26·28·30':id===2?'28~29':'25~31'}쪽 · 삼국과 가야의 생활</span>${link(textbook.url,'교과서 열기')}</div>`;
function shell(body,current='home'){
$('#app').innerHTML=`<a href="#main" class="skip">본문으로 이동</a><header class="header"><a class="brand" href="#home"><b class="brand-mark">M</b><span>MOAKIT<small>5학년 · AI × 사회</small></span></a><nav aria-label="주 메뉴"><a href="#home" ${current==='home'?'aria-current="page"':''}>수업 목차</a><a href="#library" ${current==='library'?'aria-current="page"':''}>자료실</a><a href="#museum" ${current==='museum'?'aria-current="page"':''}>우리 역사관</a><a href="#teacher" ${current==='teacher'?'aria-current="page"':''}>교사 자료</a></nav>${btn('기록 관리','settings','','small quiet')}</header><main id="main" tabindex="-1">${body}</main><footer class="site-footer"><span>MOAKIT · 삼국·가야 생활 탐구실</span><span id="save-status">${storageError?'저장된 기록을 확인하지 못했어요. 기록 관리에서 백업을 확인하세요.':'기록은 이 기기의 브라우저에 저장됩니다.'}</span></footer><dialog id="modal"></dialog>`;
}
function home(){shell(`<div class="home-wrap"><section class="cover"><div class="cover-copy"><p class="eyebrow">5학년 사회 · AI와 함께하는 역사 탐구</p><h1>유물로 살펴보는 삼국과 가야의 생활</h1><p class="lead">그림과 물건에서 옛사람들의 생활을 찾아보고, 근거를 담은 우리 모둠 역사관을 만듭니다.</p><div class="cover-actions"><a href="#lesson/1" class="button primary">첫 수업 시작하기 <span>↗</span></a><span>초등 5학년 · 10차시</span></div></div><div class="cover-visual">${photo(art('tomb'))}<span class="vertical-note">백제 / 무령왕릉</span></div></section>${bookContext(1)}<section class="contents"><div class="section-heading"><div><p class="eyebrow">OUR EXPLORATION</p><h2>열 번의 수업, 하나의 역사관</h2></div><p>발견 → 탐구 → 제작 → 나눔</p></div><ol class="lesson-list">${lessons.map(l=>`<li><a href="#lesson/${l.id}" class="lesson-link"><span class="lesson-no">${String(l.id).padStart(2,'0')}</span><span><small>${l.stage.toUpperCase()} · ${l.product}</small><strong>${l.title}</strong></span><span class="row-arrow">↗</span></a><a class="activity-shortcut" href="#activity/${l.id}">학생 활동</a></li>`).join('')}</ol></section><section class="usage"><h2>함께 보고, 직접 탐구해요.</h2><p>선생님은 수업 교재를 큰 화면에 띄웁니다. 1~3차시는 종이 활동지에 기록합니다. 2차시에서 검증한 유물을 3차시에서 소개하고, 모둠의 유물 자료는 분류·분석을 거쳐 역사관까지 이어집니다.</p><div><a href="#teacher">교사 수업 안내 ↗</a>${btn('활동 이어 하기 · 작업 파일 열기','import','','quiet')}</div></section></div>`);}
function lessonOneShell(){
 $('#app').innerHTML=`<div class="l1-shell"><a href="#main" class="skip">본문으로 이동</a><header class="l1-header"><a href="#home" class="l1-brand">MOAKIT<span>삼국과 가야의 궁금증 찾기</span></a><div class="l1-tools"><a class="button quiet" href="${worksheetUrl}" target="_blank" rel="noopener">활동지 PDF ↗</a>${btn('교사 안내','guide','data-id="1"','quiet')}<a href="#home" class="l1-home-link">수업 목차</a></div></header><main id="main" tabindex="-1">${lessonOne({step:slide,source:lessonOneSource,exampleStep:lessonOneExample,btn})}</main><dialog id="modal"></dialog></div>`;
}
function lessonTwoShell(){
 lessonTwoSource=observationIds.includes(answer('l2-selected-artifact'))?answer('l2-selected-artifact'):lessonTwoSource;
 if(!answer('l2-selected-artifact')){project.answers['l2-selected-artifact']=lessonTwoSource;save();}
 $('#app').innerHTML=`<div class="l1-shell l2-shell"><a href="#main" class="skip">본문으로 이동</a><header class="l1-header"><a href="#home" class="l1-brand">MOAKIT<span>AI의 유물 설명, 사실일까?</span></a><div class="l1-tools"><a class="button quiet" href="${worksheetFor(lessonTwoSource)}" target="_blank" rel="noopener">선택 유물 활동지 ↗</a>${btn('교사용 정답·근거','l2-prepare','','quiet')}${btn('교사 안내','guide','data-id="2"','quiet')}</div></header><main id="main" tabindex="-1">${lessonTwo({step:slide,answer,btn,source:lessonTwoSource,showReason:lessonTwoReason})}</main><dialog id="modal"></dialog></div>`;
}
function lessonThreeShell(){
 const source=answer('l2-selected-artifact');
 $('#app').innerHTML=`<div class="l1-shell l3-shell"><a href="#main" class="skip">본문으로 이동</a><header class="l1-header"><a href="#home" class="l1-brand">MOAKIT</a><div class="l1-tools">${btn('활동지','worksheet','data-id="3"','quiet')}${btn('교사 안내','guide','data-id="3"','quiet')}<a href="#home">수업 목차</a></div></header><main id="main" tabindex="-1">${lessonThree({step:slide,source,btn})}</main><dialog id="modal"></dialog></div>`;
}
function lessonView(id,activity=false){if(id===1)return lessonOneShell();if(id===2)return lessonTwoShell();if(id===3)return lessonThreeShell();const l=lessons[id-1];if(!l){location.hash='home';return;}mode=activity?'activity':'book';const page=l.pages[slide];const visual=art(lessonVisuals[id]?.[slide]||l.image);shell(`<div class="classroom ${large?'large':''}"><aside class="lesson-rail"><a href="#home" class="back">← 전체 수업</a><p class="eyebrow">삼국·가야 생활 탐구실</p><ol>${lessons.map(x=>`<li><a href="#${activity?'activity':'lesson'}/${x.id}" ${x.id===id?'aria-current="page"':''}><b>${String(x.id).padStart(2,'0')}</b><span>${x.short}</span></a></li>`).join('')}</ol><div class="rail-note">${project.records.length}개의 조사 자료<br>${project.exhibit.length}개의 전시 자료</div></aside><div class="lesson-main"><div class="lesson-toolbar"><span>${l.stage.toUpperCase()} <i> / </i> ${id}차시</span><div>${btn(large?'기본 글씨':'큰 글씨','large','','quiet small')}${btn('전체화면','fullscreen','','quiet small')}</div></div><div class="lesson-heading"><h1>${l.title}</h1><p>${l.focus}</p></div>${bookContext(id)}<div class="view-tabs" role="navigation" aria-label="교재와 활동"><a class="${activity?'':'active'}" href="#lesson/${id}">함께 보는 교재</a><a class="${activity?'active':''}" href="#activity/${id}">직접 하는 활동</a>${btn('활동지 인쇄','worksheet',`data-id="${id}"`,'quiet')}${btn('교사 안내','guide',`data-id="${id}"`,'quiet')}</div>${activity?`<section class="activity-body"><div class="activity-intro"><span class="eyebrow">오늘의 결과 · ${l.product}</span><h2>${l.short}</h2><details><summary>활동 순서 보기</summary><ol>${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol></details></div>${activityBody(id)}</section>`:`<section class="slide"><div class="slide-copy"><p class="eyebrow">${String(slide+1).padStart(2,'0')} / ${page[0]}</p><h2>${page[1]}</h2><p class="slide-text">${page[2]}</p><div class="slide-actions">${slide===4?`<a class="button primary" href="#activity/${id}">모둠 활동 열기 ↗</a>`:btn(reveal?'해설 접기':'생각한 뒤 해설 보기','reveal','','quiet')}${reveal?`<div class="explanation"><b>함께 확인해요</b><p>${page[3]}</p></div>`:''}</div></div><div class="slide-visual">${photo(visual)}<p class="source-line">${link(visual.url,visual.source)}</p></div></section><div class="pager">${btn('← 이전','prev',''+(slide===0?' disabled':''),'quiet')}<div class="page-dots" aria-label="교재 페이지">${l.pages.map((p,i)=>btn(`${i+1}`,'slide',`data-index="${i}" aria-label="${p[0]}" ${i===slide?'aria-current="step"':''}`)).join('')}</div><span class="page-count">${slide+1} / 6</span>${slide<5?btn('다음 →','next','','primary'):`<a class="button primary" href="#${id<10?'lesson/'+(id+1):'museum'}">${id<10?'다음 차시 →':'역사관 보기 →'}</a>`}</div>`}</div></div>`,'lesson');}
const recordsHint=()=>`<div class="empty"><h3>먼저 조사 자료를 모아 주세요.</h3><p>3차시에서 소개한 모둠 친구들의 유물을 자료실에서 담아 주세요. 확인한 내용은 종이 활동지를 보며 정리합니다.</p><a class="button primary" href="#library">모둠 자료 정리하기 →</a></div>`;
function recordTitle(r){return `<strong>${e(r.name)}</strong><small>${e(r.nation)} · ${e(r.kind)}</small>`;}
function activityBody(id){switch(id){
case 1:return `<p>화면의 자료를 함께 보고 종이 활동지에 짧게 기록해요.</p><a class="button quiet" href="${worksheetUrl}" target="_blank" rel="noopener">1차시 활동지 PDF ↗</a>`;
case 2:return `<p>선택한 유물의 설명을 자료로 확인하고 종이 활동지에 기록합니다.</p><a class="button quiet" href="${worksheetFor(lessonTwoSource)}" target="_blank" rel="noopener">선택 유물 활동지 PDF ↗</a>`;
case 3:return lessonThree({step:slide,source:answer('l2-selected-artifact'),btn});
case 4:return !project.records.length?recordsHint():`${input('criterion','우리의 분류 기준','예: 쓰임 / 재료 / 나라')}<p class="notice">우리 분류를 먼저 적고, 같은 기준으로 실제 AI에게 분류를 부탁해 비교하세요.</p>${btn('AI에게 줄 요청문 만들기','classify-prompt','','quiet')}<div class="table-wrap"><table><thead><tr><th>자료</th><th>우리 분류</th><th>실제 AI 분류</th></tr></thead><tbody>${project.records.map(r=>`<tr><th scope="row">${e(r.name)}</th><td><input aria-label="${e(r.name)} 우리 분류" data-answer="class-${r.id}" value="${e(answer('class-'+r.id))}" placeholder="우리가 정한 묶음"></td><td><input aria-label="${e(r.name)} AI 분류" data-answer="ai-class-${r.id}" value="${e(answer('ai-class-'+r.id))}" placeholder="실행한 뒤 기록"></td></tr>`).join('')}</tbody></table></div>${input('classify-tool','실제로 사용한 AI · 사용 날짜')}${field('classify-reason','다르게 나눈 자료와 그 이유')}${field('classify-change','기준을 바꾼다면 어떻게 묶을 수 있을까요?')}`;
case 5:return !project.records.length?recordsHint():`<p>단어 두 개를 잇고, 그 사이에 들어갈 설명을 적어 보세요.</p><form id="relation-form"><div class="two-cols"><label class="field"><span>첫 번째 대상</span><input name="from" list="targets" required maxlength="80" placeholder="예: 신라 금관"></label><label class="field"><span>두 번째 대상</span><input name="to" list="targets" required maxlength="80" placeholder="예: 금속 공예"></label></div><datalist id="targets">${[...project.records.map(r=>r.name),'고구려','백제','신라','가야','생활 모습','공예 기술','믿음'].map(x=>`<option value="${e(x)}">`).join('')}</datalist><label class="field"><span>연결 문장</span><input name="label" required maxlength="300" placeholder="예: 금으로 만든 장식에서 공예 기술을 알 수 있다"></label><div class="two-cols"><label class="field"><span>이 연결은</span><select name="status"><option>확인한 사실</option><option>우리의 추측</option></select></label><label class="field"><span>근거 자료</span><select name="source">${project.records.map(r=>`<option value="${r.id}">${e(r.name)}</option>`).join('')}</select></label></div><button class="primary" type="submit">관계도에 연결하기 +</button></form>${relationsMarkup()}${field('relation-comparison','두 나라 자료에서 찾은 공통점과 차이점')}`;
case 6:return !project.records.length?recordsHint():`<div class="two-cols"><label class="field"><span>분석할 자료</span><select id="word-nation">${['전체','고구려','백제','신라','가야'].map(n=>`<option ${wordNation===n?'selected':''}>${n}</option>`).join('')}</select></label>${input('keywords','찾을 낱말 · 쉼표로 구분','예: 무덤, 금, 사람, 장식, 돌')}</div><p class="notice">우리가 쓴 자료 설명에서 입력한 글자가 등장한 횟수를 셉니다. AI 분석이 아니며, “금”은 “금동”에도 포함되어 셉니다.</p>${btn('낱말 분석하기','words','','primary')}<div id="word-result">${wordMarkup()}</div>${field('word-meaning','원문을 읽고 해석한 특징')}${field('word-limit','이 결과만으로 알 수 없는 것')}`;
case 7:return !project.records.length?recordsHint():`<div class="callout"><small>우리의 탐구 질문</small><p>${e(answer('question-final')||answer('question')||'2차시에서 질문을 정해 주세요.')}</p></div>${input('museum-title','역사관 이름','예: 유물 속 삼국의 기술')}${field('museum-intro','관람객에게 전하고 싶은 이야기')}${input('museum-nation','전시할 나라 / 비교할 나라','예: 고구려·백제·신라')}<h3>전시할 자료를 골라요.</h3><div class="selection-list">${project.records.map(r=>`<label><input type="checkbox" data-exhibit="${r.id}" ${project.exhibit.includes(r.id)?'checked':''}>${e(r.name)}<small>${e(r.nation)}</small></label>`).join('')}</div><h3>관람 순서</h3>${project.exhibit.length?selectedRecords(project).map((r,i)=>`<div class="order-row"><b>${i+1}</b><span>${e(r.name)}</span>${btn('↑','move-up',`data-id="${r.id}" aria-label="${e(r.name)} 앞으로" ${i===0?'disabled':''}`,'quiet')}${btn('↓','move-down',`data-id="${r.id}" aria-label="${e(r.name)} 뒤로" ${i===project.exhibit.length-1?'disabled':''}`,'quiet')}</div>`).join(''):'<p class="empty">위에서 전시할 자료를 선택하세요.</p>'}${field('museum-plan','이 순서로 전시하는 이유')}`;
case 8:return !project.exhibit.length?`<div class="empty"><h3>먼저 역사관을 설계해 주세요.</h3><a class="button primary" href="#activity/7">전시 자료 선택하기 →</a></div>`:`<p class="notice">초안을 쓴 뒤 출처를 읽고 수정하세요. 직접 쓴 경우에도 같은 방법으로 확인합니다.</p>${selectedRecords(project).map(r=>`<article class="exhibit-editor"><div class="record-head"><h3>${e(r.name)}</h3>${btn('해설 요청문 만들기','draft-prompt',`data-id="${r.id}"`,'quiet small')}</div><p>${link(r.url,r.source)}</p>${select('method-'+r.id,'초안 작성 방식',['직접 작성','교사와 AI 사용'])}${field('draft-'+r.id,'확인 전 초안')}${field('change-'+r.id,'근거와 대조해서 고친 부분')}${field('final-'+r.id,'관람객에게 보여 줄 최종 해설')}${field('guess-'+r.id,'추측한 생활 모습 · 근거도 함께 쓰기','확인한 사실과 구분해서 씁니다.')}<label class="check"><input type="checkbox" data-verified="${r.id}" ${project.checked.includes(r.id)?'checked':''}>출처를 읽고 최종 해설의 사실을 확인했습니다.</label></article>`).join('')}<a class="button primary" href="#museum">관람객 화면 보기 ↗</a>`;
case 9:return `${input('peer-group','우리가 관람한 모둠 이름')}<p class="notice">친구의 관람용 HTML 파일을 열거나 기기를 바꿔 관람하세요. 친구의 작업 JSON을 가져오면 내 기록이 교체되므로 관람에 사용하지 않습니다.</p>${field('peer-claim','확인한 해설 문장')}${select('peer-status','확인 결과',['확인 필요','자료와 일치','자료와 다름','근거 부족'])}${field('peer-evidence','확인한 출처와 근거')}${field('peer-feedback','친구에게 전할 수정 제안')}${field('received','우리 모둠이 받은 피드백')}${field('before-revision','우리의 수정 전 문장')}${field('after-revision','수정한 문장과 이유')}<a href="#activity/8" class="button primary">우리 역사관 해설에 반영하기 →</a>`;
case 10:return `<div class="callout"><small>우리의 첫 질문</small><p>${e(answer('curious')||answer('question')||'아직 기록한 질문이 없습니다.')}</p></div><a class="button primary" href="#museum">역사관 발표하기 ↗</a>${field('presentation','발표 메모','우리 질문 → 중요한 자료 → 추론한 생활 → AI의 도움과 한계')}${field('learned','처음 생각과 달라진 점 · 근거가 된 자료')}${field('human-role','AI가 도운 일과 우리가 직접 판단한 일')}${field('my-role','내가 맡은 일과 다음에 더 해 보고 싶은 일')}<h3>우리 반의 AI 사용 약속 다섯 가지</h3><p>예시를 읽고 우리 반이 실천할 말로 바꾸어 적어요.</p>${promises.map((p,i)=>input('promise-'+i,`${i+1}. ${p}`,'우리 반의 약속을 적어 주세요.')).join('')}${btn('탐구 기록 인쇄','report','','quiet')}`;
}}
function relationsMarkup(){return `<section class="relations"><h3>우리의 역사 관계도</h3>${project.relations.length?project.relations.map(r=>{const source=project.records.find(x=>x.id===r.source);return `<article class="relation"><div class="relation-flow"><strong>${e(r.from)}</strong><span><small>${e(r.status)}</small>${e(r.label)}<i aria-hidden="true">→</i></span><strong>${e(r.to)}</strong></div><div class="relation-source">근거: ${source?link(source.url,source.name):'자료를 다시 연결해 주세요.'}${btn('연결 삭제','remove-relation',`data-id="${e(r.id)}"`,'quiet small')}</div></article>`;}).join(''):'<p class="empty">첫 연결을 만들면 여기에 관계도가 나타납니다.</p>'}</section>`;}
function wordMarkup(){const rs=project.records.filter(r=>wordNation==='전체'||r.nation===wordNation);const text=rs.map(r=>r.fact).join('\n');const counts=wordCounts(text,answer('keywords'));const max=Math.max(1,...counts.map(x=>x.count));return `<div class="word-panel"><div class="section-heading"><h3>${e(wordNation)} 자료 속 낱말</h3><small>자료 ${rs.length}개 · 설명 ${text.length}자</small></div>${counts.length?`<div class="word-cloud">${counts.filter(x=>x.count).map(x=>`<span style="font-size:${18+Math.round(x.count/max*28)}px">${e(x.word)}</span>`).join('')||'<p>찾는 낱말이 없습니다.</p>'}</div><div class="bars">${counts.map(x=>`<div class="bar-row"><span>${e(x.word)}</span><div><i style="width:${x.count/max*100}%"></i></div><b>${x.count}회</b></div>`).join('')}</div>`:'<p>비교하고 싶은 낱말을 입력한 뒤 분석해 보세요.</p>'}<details><summary>분석한 원문 보기</summary>${rs.map(r=>`<h4>${e(r.name)}</h4><p>${e(r.fact)||'작성한 특징이 없습니다.'}</p>`).join('')||'<p>이 나라의 조사 자료가 없습니다.</p>'}</details></div>`;}
function comparison(){const chosen=compareIds.map(art).filter(Boolean);return `<section class="compare-area" aria-label="자료 비교"><div class="section-heading"><h2>두 자료를 함께 살펴보기</h2><span>${chosen.length}/2 선택</span></div>${chosen.length?`<div class="two-cols">${chosen.map(a=>`<article><small>${a.nation} · ${bookLabel(a)}</small><h3>${a.name}</h3><p>${a.fact}</p>${btn('선택 해제','compare',`data-id="${a.id}"`,'quiet small')}</article>`).join('')}</div>`:'<p>자료에서 ‘비교하기’를 눌러 두 개를 골라 주세요.</p>'}${chosen.length===2?`${field(comparisonKey('common'),'두 자료의 공통점')}${field(comparisonKey('different'),'두 자료의 차이점')}${field(comparisonKey('evidence'),'자료를 보고 알게 된 생활 모습','어느 자료의 어떤 부분이 근거인가요?')}`:''}</section>`;}
function library(){const shown=artifacts.filter(a=>(showExtra||a.core)&&(filter==='전체'||a.nation===filter)&&(themeFilter==='전체'||a.theme===themeFilter));shell(`<div class="page-wrap"><p class="eyebrow">교과서 자료실</p><h1>삼국과 가야 사람들의 생활</h1><p class="lead">자료를 골라 살펴보고, 다른 나라의 자료와 비교해 보세요.</p>${bookContext(3)}<div class="filters" aria-label="나라별 자료">${['전체','고구려','백제','신라','가야'].map(n=>btn(n,'filter',`data-filter="${n}" aria-pressed="${filter===n}"`,filter===n?'primary':'quiet')).join('')}</div><div class="filters" aria-label="생활 주제별 자료">${themes.map(n=>btn(n,'theme-filter',`data-filter="${n}" aria-pressed="${themeFilter===n}"`,themeFilter===n?'primary':'quiet')).join('')}</div><label class="extra-toggle"><input type="checkbox" id="show-extra" ${showExtra?'checked':''}> 추가 탐구 자료도 보기</label>${comparison()}<p class="result-count" role="status">${shown.length}개의 자료</p><div class="archive-grid">${shown.map(a=>`<article>${photo(a)}<div class="archive-copy"><small>${a.nation} · ${bookLabel(a)} · ${a.theme}</small><h2>${a.name}</h2><p>${a.fact}</p><details><summary>생각할 때 주의할 점</summary><p class="caution">${a.caution}</p></details><p>${link(a.url,a.source)}</p><div class="archive-actions">${btn(project.records.some(r=>r.base===a.id)?'조사표에 담았어요':'조사표에 담기 +','collect',`data-id="${a.id}" ${project.records.some(r=>r.base===a.id)?'disabled':''}`,'primary')}${btn(compareIds.includes(a.id)?'비교 선택됨':'비교하기','compare',`data-id="${a.id}" aria-pressed="${compareIds.includes(a.id)}"`,'quiet')}</div></div></article>`).join('')||'<p class="empty">이 조건의 자료가 없습니다. 나라나 주제를 바꾸어 주세요.</p>'}</div><p class="notice">교과서 사진은 연결된 원문 또는 종이 교과서에서 봅니다. 웹교재의 설명과 질문은 수업을 위해 새로 작성했습니다. 추가 탐구 자료는 교과서 본문 자료와 구분합니다.</p></div>`,'library');}
function museumContent(exported=false){const rs=selectedRecords(project);return `<section class="museum-cover"><p class="eyebrow">우리 모둠 역사관 / 삼국과 가야</p><h1>${e(answer('museum-title')||'우리 모둠의 역사관')}</h1><p>${e(project.school)} ${e(project.group)}</p><p class="museum-intro">${e(answer('museum-intro')||'전시할 이야기를 7차시에서 정해 주세요.')}</p>${answer('question-final')||answer('question')?`<div class="museum-question">탐구 질문 · ${e(answer('question-final')||answer('question'))}</div>`:''}</section>${rs.map((r,i)=>`<article class="museum-object"><div>${r.base&&art(r.base)?photo(art(r.base)):`<div class="text-artifact"><span>기록 자료</span><h2>${e(r.name)}</h2><p>${e(r.fact)}</p></div>`}</div><div class="museum-caption"><p class="eyebrow">EXHIBIT ${String(i+1).padStart(2,'0')} / ${e(r.nation)}</p><h2>${e(r.name)}</h2><p class="verification ${project.checked.includes(r.id)?'verified':''}">${project.checked.includes(r.id)?'모둠이 출처를 확인한 해설':'아직 확인 중인 해설'}</p><p class="final-caption">${e(answer('final-'+r.id)||'아직 해설을 작성하지 않았습니다.')}</p>${answer('guess-'+r.id)?`<div class="inference"><strong>우리의 추측</strong><p>${e(answer('guess-'+r.id))}</p></div>`:''}<p class="metadata">${e(r.period)} · ${e(r.material)}</p><p class="source-line">${link(r.url,r.source)}</p></div></article>`).join('')}${project.relations.length?relationsMarkup():''}${answer('word-meaning')?`<section class="museum-analysis"><h2>자료를 분석하며 발견한 것</h2><p>${e(answer('word-meaning'))}</p><p class="caution">${e(answer('word-limit'))}</p></section>`:''}`;}
function museum(){shell(`<div class="museum-page"><div class="museum-tools"><a href="#activity/7">← 전시 설계</a><div><a class="button quiet" href="#activity/8">해설 수정</a>${btn('관람 파일 내려받기','export-museum',''+(!project.exhibit.length?' disabled':''),'primary')}${btn('인쇄','print','','quiet')}</div></div>${project.exhibit.length?museumContent():`<div class="empty museum-empty"><p class="eyebrow">아직 문을 열기 전이에요</p><h1>우리의 자료로 역사관을 만들어요.</h1><p>조사한 자료에서 전시물을 고르고, 해설과 출처를 붙이면 이곳에 나타납니다.</p><a href="#activity/7" class="button primary">역사관 설계하기 →</a></div>`}</div>`,'museum');}
function teacher(){shell(`<div class="page-wrap teacher"><p class="eyebrow">TEACHER'S DESK</p><h1>수업을 여는 선생님께</h1><p class="lead">10차시 동안 쌓은 자료로 하나의 역사관을 완성합니다.</p><div class="teacher-overview"><div><h2>한 차시 40분 · 운영 예시</h2><ol><li><b>5분</b> 질문과 사진 관찰</li><li><b>7분</b> 개념 설명과 활동 시범</li><li><b>23분</b> 모둠 탐구·제작</li><li><b>5분</b> 기록·나눔·다음 차시 연결</li></ol></div><div><h2>수업 전 준비</h2><ul><li>비상교육 사회 5-2(2022 개정) 25~31쪽</li><li>교과서의 사진과 웹교재 질문을 함께 사용</li><li>1~3차시: 학생별 활동지와 필기구 (3차시는 2차시 활동지 지참)</li><li>4차시부터: 모둠별 태블릿 또는 노트북 1대</li><li>큰 화면으로 교재 투사</li><li>4·8차시: 교사가 관리하는 생성형 AI</li><li>사용할 공식 자료를 미리 열어 접속 확인</li><li>매 수업 후 작업 파일을 내려받아 보관</li></ul></div></div><p class="notice">1~3차시는 종이 활동지에 기록합니다. 이후의 웹 기록은 현재 브라우저에 저장됩니다. 자동 계정 동기화와 실시간 모둠 공유는 포함하지 않았습니다. 다른 기기에서는 작업 JSON을 가져오고, 서로 관람할 때는 관람용 HTML을 사용합니다.</p><div class="table-wrap"><table><thead><tr><th>차시 · 단계</th><th>수업과 결과물</th><th>관찰할 점</th><th>자료</th></tr></thead><tbody>${lessons.map(l=>`<tr><td>${l.id} · ${l.stage}</td><td><a href="#lesson/${l.id}">${l.title}</a><small>${l.product}</small></td><td>${l.guide.watch}</td><td>${btn('지도안','guide',`data-id="${l.id}"`,'quiet small')}${btn('활동지','worksheet',`data-id="${l.id}"`,'quiet small')}</td></tr>`).join('')}</tbody></table></div><h2>관찰과 피드백 기준</h2><div class="table-wrap"><table><thead><tr><th>관찰 영역</th><th>성장의 근거</th><th>도움을 주는 질문</th></tr></thead><tbody><tr><td>자료와 출처</td><td>출처를 열어 주장을 확인한다.</td><td>어디에서 그렇게 말하고 있나요?</td></tr><tr><td>분류와 분석</td><td>기준·자료 범위·한계를 설명한다.</td><td>기준이나 자료를 바꾸면 달라질까요?</td></tr><tr><td>검증과 수정</td><td>사실과 추측을 나누고 근거로 고친다.</td><td>왜 그 문장을 바꾸었나요?</td></tr><tr><td>협력과 성찰</td><td>역할을 나누고 자신의 판단을 설명한다.</td><td>AI가 도운 일과 직접 한 일은 무엇인가요?</td></tr></tbody></table></div><h2>AI를 사용할 수 없을 때</h2><p>2차시는 준비된 학습용 문장을 검증하고, 4차시는 교사 시연 결과를 기록합니다. 8차시는 직접 해설을 쓰도록 작성 방식을 표시합니다. 실행하지 않은 결과를 AI가 만든 것으로 표시하지 않습니다.</p></div>`,'teacher');}
function modal(html){const d=$('#modal');d.innerHTML=`<div class="modal-top">${btn('닫기 ×','close','','quiet')}</div>${html}`;d.showModal();}
function guide(id){const l=lessons[id-1];modal(`<div class="printable"><p class="eyebrow">교사용 수업 안내 · ${l.stage}</p><h2>${id}차시 ${l.title}</h2><p>${l.focus}</p><h3>교과서 연계</h3>${bookContext(id)}<p>생활 모습을 보여 주는 유물·유적을 관찰하고 서로 비교합니다. ${id===1?'1차시는 여섯 자료의 사진을 화면에서 바로 관찰합니다.':'교과서 사진은 원문에서 확인하세요.'}</p><h3>준비물</h3><p>${l.guide.prep}</p><h3>40분 흐름</h3><p>${id===1?'둘러보기 6분 / 단서 찾기 8분 / 함께 연습 7분 / 모둠 질문 8분 / 알아볼 방법 7분 / 나눔 4분':id===2?'질문 다시 보기 5분 / 비교 연습 6분 / 실제 AI 답변 비교 10분 / 자료로 확인 9분 / 질문 다듬기 7분 / 다음 탐구 3분':'관찰·질문 5분 / 개념·시범 7분 / 모둠 활동 23분 / 정리 5분'}</p><ol>${l.steps.map(x=>`<li>${x}</li>`).join('')}</ol><h3>관찰할 점</h3><p>${l.guide.watch}</p><h3>오개념 주의</h3><p>${l.guide.misconception}</p><h3>화면별 해설</h3>${l.pages.map(p=>`<p><b>${p[0]} · ${p[1]}</b><br>${p[3]}</p>`).join('')}</div>${btn('지도안 인쇄','print','','primary')}`);}
function worksheet(id){if(id===3){modal(thirdWorksheet(answer('l2-selected-artifact'),project.school,project.group)+btn('활동지 인쇄 · PDF 저장','print','','primary'));return;}if(id===2){window.open(worksheetFor(lessonTwoSource),'_blank','noopener');return;}if(id===1){window.open(worksheetUrl,'_blank','noopener');return;}const l=lessons[id-1];const prompts={1:['고른 자료 이름과 직접 본 특징','자료를 보고 생긴 궁금증과 우리 모둠의 질문','AI에게 부탁할 일과 우리가 확인할 자료'],2:['우리 모둠의 탐구 질문','실제 AI 답변에서 다르게 말한 부분','확인한 출처와 다듬은 질문'],3:['자료 이름 / 나라 / 시대 / 종류','우리 질문과 관련된 특징','출처의 기관 이름과 주소'],4:['분류 기준과 우리 분류','실제 AI의 분류와 다른 부분','차이가 생긴 이유 / 바꾸어 볼 기준'],5:['서로 연결할 두 대상','연결 문장 / 사실 또는 추측','연결의 근거 / 공통점과 차이점'],6:['분석한 자료와 찾은 낱말','자주 나온 낱말과 횟수','원문으로 확인한 특징과 분석의 한계'],7:['역사관 제목과 탐구 질문','전시할 자료와 순서','관람객에게 전하고 싶은 이야기'],8:['초안의 한 문장과 작성 방식','공식 자료에서 확인한 내용','최종 해설과 고친 이유'],9:['친구의 역사관에서 확인한 문장','확인한 출처와 피드백','우리 모둠이 고친 문장과 이유'],10:['우리 질문과 중요한 발견','AI가 도운 일 / 내가 직접 한 일','다음 탐구에서 지킬 약속']};modal(`<article class="worksheet printable"><header><span>${e(project.school)||'MOAKIT'} · AI × 사회</span><span>5학년 · ${id}차시</span></header><h2>${l.short}</h2><p>모둠: ${e(project.group)||'____________'}　이름: ____________　날짜: ____________</p><p class="worksheet-question">${l.question}</p>${prompts[id].map((p,i)=>`<section><h3>${i+1}. ${p}</h3><div class="writing-lines"></div></section>`).join('')}<footer>나의 오늘 한마디: __________________________________________________</footer></article>${btn('활동지 인쇄 · PDF 저장','print','','primary')}`);}
function settings(){modal(`<h2>우리 모둠의 탐구 기록</h2><p>자동 저장은 이 기기의 브라우저 안에서만 이루어집니다. 수업을 마치면 작업 파일을 내려받아 주세요.</p><label class="field"><span>학교 이름 · 활동지 머리글</span><input data-meta="school" maxlength="100" value="${e(project.school)}" placeholder="예: 보성초등학교"></label><label class="field"><span>모둠 이름</span><input data-meta="group" maxlength="100" value="${e(project.group)}" placeholder="예: 역사탐구 1모둠"></label><div class="settings-actions">${btn('작업 파일 내려받기','export','','primary')}${btn('작업 파일 가져오기','import','','quiet')}${btn('탐구 기록 인쇄','report','','quiet')}</div><p class="notice">작업 파일(JSON)은 이어서 편집할 때, 역사관 관람 파일(HTML)은 다른 모둠에게 보여 줄 때 사용합니다.</p><details><summary>새 모둠 시작</summary><p>현재 기기의 기록을 지웁니다. 먼저 작업 파일을 내려받아 보관하세요.</p>${btn('기록 비우기','reset','','danger')}</details>`);}
function artifactModal(id){const a=art(id);modal(`<h2>${a.name}</h2>${photo(a)}<p>${a.fact}</p><p><b>사진 관찰</b> · ${a.observe}</p><p class="caution">${a.caution}</p><p>${link(a.url,a.source)}</p>${btn(project.records.some(r=>r.base===id)?'조사표에 담았어요':'조사표에 담기','collect',`data-id="${id}" ${project.records.some(r=>r.base===id)?'disabled':''}`,'primary')}`);}
function recordForm(){modal(`<h2>직접 찾은 자료 추가</h2><form id="record-form">${[['name','자료 이름'],['period','시대'],['kind','종류'],['material','재료'],['source','자료를 제공한 기관'],['url','출처 주소 · https://']].map(([k,v])=>`<label class="field"><span>${v}</span><input name="${k}" required maxlength="500" ${k==='url'?'type="url"':''}></label>`).join('')}<label class="field"><span>나라</span><select name="nation"><option>고구려</option><option>백제</option><option>신라</option><option>가야</option><option>비교 자료</option></select></label><label class="field"><span>확인한 특징</span><textarea name="fact" required maxlength="12000"></textarea></label><button class="primary" type="submit">조사표에 추가</button></form>`);}
function collect(id){if(project.records.some(r=>r.base===id))return;if(project.records.length>=40)return toast('조사 자료는 40개까지 담을 수 있어요.');const a=art(id);project.records.push({id:a.id,base:a.id,name:a.name,nation:a.nation,period:a.period,kind:a.kind,material:a.material,fact:'',source:a.source,url:a.url});save();$('#modal')?.close();render();toast('조사표에 담았어요. 읽고 확인한 특징을 우리 말로 적어 주세요.');}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function report(){modal(`<article class="printable report"><h2>우리 모둠의 삼국시대 탐구 기록</h2><p>${e(project.school)} · ${e(project.group)}</p>${lessons.map(l=>`<section><h3>${l.id}차시 · ${l.short}</h3>${reportLesson(l.id)}</section>`).join('')}</article>${btn('기록 인쇄 · PDF 저장','print','','primary')}`);}
function reportLesson(id){if(id===2)return '<p>2차시는 선택한 유물의 종이 활동지에 예상·출처·근거·최종 판단을 기록합니다.</p>';if(id===1)return lessonOneReport(answer);const mapping={1:['observed','inference','curious','ai-help'],2:['question','ai-first','ai-second','ai-tool','claim','claim-source','question-final'],4:['criterion','classify-tool','classify-reason','classify-change'],5:['relation-comparison'],6:['keywords','word-meaning','word-limit'],7:['museum-title','museum-intro','museum-plan'],9:['peer-group','peer-claim','peer-status','peer-evidence','peer-feedback','received','before-revision','after-revision'],10:['presentation','learned','human-role','my-role',...promises.map((_,i)=>'promise-'+i)]};const labels={'observed':'보이는 것','inference':'추측','curious':'궁금한 점','ai-help':'AI에게 부탁할 일','question':'탐구 질문','ai-first':'첫 답변','ai-second':'두 번째 답변','ai-tool':'사용한 AI','claim':'확인할 주장','claim-source':'확인한 근거','question-final':'다듬은 질문','criterion':'분류 기준','classify-tool':'사용한 AI','classify-reason':'분류 차이와 이유','classify-change':'바꿀 기준','relation-comparison':'공통점과 차이','keywords':'분석 낱말','word-meaning':'해석','word-limit':'한계','museum-title':'전시 제목','museum-intro':'소개','museum-plan':'전시 순서의 이유','peer-group':'관람한 모둠','peer-claim':'확인한 문장','peer-status':'판정','peer-evidence':'근거','peer-feedback':'제안','received':'받은 피드백','before-revision':'수정 전','after-revision':'수정 후와 이유','presentation':'발표 메모','learned':'알게 된 점','human-role':'AI와 사람의 역할','my-role':'나의 역할'};let result=(mapping[id]||[]).filter(k=>answer(k)).map(k=>`<p><b>${labels[k]||'AI 사용 약속'}:</b> ${e(answer(k))}</p>`).join('');if(id===1)result=`<p><b>관찰한 자료:</b> ${e(art('susan').name)}</p>`+result;if(id===3)result=project.records.map(r=>`<p><b>${e(r.name)} · ${e(r.nation)}</b><br>${e(r.fact)}<br>${link(r.url,r.source)}</p>`).join('');if(id===4)result+=project.records.map(r=>`<p>${e(r.name)} · 우리: ${e(answer('class-'+r.id))} / AI: ${e(answer('ai-class-'+r.id))}</p>`).join('');if(id===5)result+=relationsMarkup();if(id===7)result+=`<p>전시 순서: ${selectedRecords(project).map(r=>e(r.name)).join(' → ')}</p>`;if(id===8)result=selectedRecords(project).map(r=>`<h4>${e(r.name)}</h4><p>초안: ${e(answer('draft-'+r.id))}</p><p>수정 이유: ${e(answer('change-'+r.id))}</p><p>최종 해설: ${e(answer('final-'+r.id))}</p>`).join('');return result||'<p>아직 기록하지 않았습니다.</p>';}
async function exportMuseum(){const incomplete=readiness(project).filter(x=>!x.ready);if(incomplete.length&&!confirm(`${incomplete.length}개의 전시물에 해설 또는 출처 확인이 남아 있어요. 확인 중 표시가 있는 관람 파일로 내려받을까요?`))return;toast('관람 파일을 준비하고 있어요.');try{const css=await fetch('style.css').then(r=>{if(!r.ok)throw Error();return r.text();});const container=document.createElement('div');container.innerHTML=museumContent(true);container.querySelectorAll('button').forEach(x=>x.remove());// Embed only bundled assets; project text never determines a fetch URL.
const dataUrl=async(url)=>{const r=await fetch(url);if(!r.ok)throw Error('사진 파일을 읽지 못했어요.');const b=await r.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(b);});};
for(const img of container.querySelectorAll('img')){img.src=await dataUrl(img.getAttribute('src'));img.removeAttribute('loading');}let embeddedCss=css;for(const font of ['5Medium','7ExtraBold']){const path=`assets/fonts/S-CoreDream-${font}.woff2`;embeddedCss=embeddedCss.replaceAll(path,await dataUrl(path));}const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(answer('museum-title')||'삼국시대 역사관')}</title><style>${embeddedCss}</style><body class="exported"><main class="museum-page">${container.innerHTML}</main><footer class="site-footer">MOAKIT · 학생 모둠 제작 · 사실 여부는 연결된 출처와 함께 확인하세요.</footer></body></html>`;download('삼국시대-역사관-관람.html',html,'text/html;charset=utf-8');toast('관람 파일을 내려받았어요. 교과서 사진은 파일의 링크를 열어 확인하세요.');}catch{toast('관람 파일을 만들지 못했어요. 연결을 확인하고 다시 시도해 주세요.');}}
function promptModal(text){modal(`<h2>선생님과 AI에게 부탁해요</h2><p>아래 요청문을 복사해 교사가 준비한 AI에서 사용하세요. 결과는 활동 화면에 직접 기록합니다.</p><label class="field"><span>요청문</span><textarea id="prompt-text" rows="10" readonly>${e(text)}</textarea></label>${btn('요청문 복사','copy-prompt','','primary')}`);}
function render(){const [route,n]=location.hash.slice(1).split('/');if(route==='lesson'||route==='activity'){const id=Number(n);if(Number.isInteger(id)&&id>=1&&id<=10)return lessonView(id,route==='activity');}if(route==='library')return library();if(route==='museum')return museum();if(route==='teacher')return teacher();home();}
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.answer){project.answers[el.dataset.answer]=el.value;if(el.dataset.answer.startsWith('final-'))project.checked=project.checked.filter(id=>'final-'+id!==el.dataset.answer);save();if(el.dataset.answer.startsWith('final-')){const checkbox=$(`[data-verified="${el.dataset.answer.slice(6)}"]`);if(checkbox)checkbox.checked=false;}}if(el.dataset.meta){project[el.dataset.meta]=el.value;save();}if(el.dataset.record){const r=project.records.find(x=>x.id===el.dataset.record);r.fact=el.value;project.checked=project.checked.filter(id=>id!==r.id);save();}});
document.addEventListener('change',event=>{const el=event.target;if(el.id==='show-extra'){showExtra=el.checked;render();}if(el.dataset.answer==='observation-artifact'){project.answers['observation-artifact']=el.value;save();render();}if(el.dataset.exhibit){const id=el.dataset.exhibit;project.exhibit=el.checked?[...project.exhibit,id]:project.exhibit.filter(x=>x!==id);save();render();}if(el.dataset.verified){const id=el.dataset.verified;if(el.checked&&!answer('final-'+id).trim()){el.checked=false;return toast('최종 해설을 먼저 작성해 주세요.');}project.checked=el.checked?[...new Set([...project.checked,id])]:project.checked.filter(x=>x!==id);save();}if(el.id==='word-nation'){wordNation=el.value;$('#word-result').innerHTML=wordMarkup();}});
document.addEventListener('submit',event=>{event.preventDefault();const f=event.target;const d=Object.fromEntries(new FormData(f));if(f.id==='record-form'){if(!safeUrl(d.url))return toast('https://로 시작하는 출처 주소를 넣어 주세요.');if(project.records.length>=40)return toast('자료는 40개까지 추가할 수 있어요.');project.records.push({...d,id:'r-'+crypto.randomUUID(),base:''});save();$('#modal').close();render();toast('새 자료를 조사표에 추가했어요.');}if(f.id==='relation-form'){if(project.relations.length>=50)return toast('관계는 50개까지 연결할 수 있어요.');if(d.from.trim()===d.to.trim())return toast('서로 다른 두 대상을 골라 주세요.');project.relations.push({...d,id:'rel-'+crypto.randomUUID()});save();render();}});
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=el.dataset.id;
if(action==='l3-step'){slide=Math.max(0,Math.min(2,Number(el.dataset.step)));render();window.scrollTo(0,0);return;}
if(action==='l2-step'){slide=Math.max(0,Math.min(5,Number(el.dataset.step)));render();window.scrollTo(0,0);return;}
if(action==='l2-source'&&observationIds.includes(id)){lessonTwoSource=id;project.answers['l2-selected-artifact']=id;save();render();return;}
if(action==='l2-reason'){lessonTwoReason=!lessonTwoReason;render();return;}
if(action==='l2-prepare'){modal(teacherForm(lessonTwoSource));return;}

if(action==='l1-example'){lessonOneExample=Math.max(0,Math.min(2,Number(el.dataset.example)));render();return;}
if(action==='l1-step'){slide=Math.max(0,Math.min(5,Number(el.dataset.step)));render();window.scrollTo(0,0);return;}
if(['l1-object','l1-open'].includes(action)&&observationIds.includes(id)){lessonOneSource=id;if(action==='l1-open')slide=1;render();if(action==='l1-open')window.scrollTo(0,0);return;}
if(action==='settings')settings();if(action==='close'){$('#modal').close();if(['home','museum','teacher'].includes(location.hash.slice(1)))render();}if(action==='guide')guide(+id);if(action==='worksheet')worksheet(+id);if(action==='print')window.print();if(action==='report')report();
if(action==='next'){slide=Math.min(5,slide+1);reveal=false;render();}if(action==='prev'){slide=Math.max(0,slide-1);reveal=false;render();}if(action==='slide'){slide=+el.dataset.index;reveal=false;render();}if(action==='reveal'){reveal=!reveal;render();}if(action==='large'){large=!large;render();}if(action==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('이 기기에서는 큰 글씨 모드를 사용해 주세요.');}catch{toast('전체화면을 열지 못했어요. 큰 글씨 모드로 수업할 수 있어요.');}}
if(action==='theme-filter'){themeFilter=el.dataset.filter;render();}if(action==='compare'){const selected=compareIds.includes(id);if(!selected&&compareIds.length>=2)return toast('먼저 선택한 자료 하나를 해제해 주세요.');compareIds=selected?compareIds.filter(x=>x!==id):[...compareIds,id];project.answers['compare-selected']=compareIds.join(',');save();render();}
if(action==='filter'){filter=el.dataset.filter;render();}if(action==='artifact')artifactModal(id);if(action==='collect')collect(id);if(action==='add-record')recordForm();if(action==='remove-record'&&confirm('조사표와 전시에서 이 자료를 뺄까요? 관련 해설·분류·관계도도 삭제됩니다.')){project.records=project.records.filter(x=>x.id!==id);project.exhibit=project.exhibit.filter(x=>x!==id);project.checked=project.checked.filter(x=>x!==id);project.relations=project.relations.filter(x=>x.source!==id);for(const prefix of ['class-','ai-class-','draft-','final-','change-','guess-','method-'])delete project.answers[prefix+id];save();render();}if(action==='remove-relation'){project.relations=project.relations.filter(x=>x.id!==id);save();render();}
if(action==='words')$('#word-result').innerHTML=wordMarkup();if(action==='move-up'||action==='move-down'){const i=project.exhibit.indexOf(id),j=i+(action==='move-up'?-1:1);if(j>=0&&j<project.exhibit.length){[project.exhibit[i],project.exhibit[j]]=[project.exhibit[j],project.exhibit[i]];save();render();}}
if(action==='export')download('5class-삼국시대-작업.json',JSON.stringify(project,null,2),'application/json');if(action==='import')$('#import-file').click();if(action==='reset'&&confirm('현재 기기의 모든 탐구 기록을 지울까요? 내려받지 않은 기록은 되돌릴 수 없습니다.')){project=fresh();compareIds=[];save();$('#modal').close();render();toast('새 모둠의 기록을 시작합니다.');}if(action==='export-museum')await exportMuseum();if(action==='classify-prompt')promptModal(`초등 5학년 역사 탐구입니다. 다음 자료를 "${answer('criterion')||'쓰임'}" 기준으로 분류해 주세요. 각 자료의 묶음과 이유를 표로 정리하고, 근거가 부족하면 확인 필요라고 써 주세요.\n\n${project.records.map(r=>`${r.name}: ${r.fact||'(특징 미작성)'}`).join('\n')}`);if(action==='draft-prompt'){const r=project.records.find(x=>x.id===id);promptModal(`초등 5학년 역사관 해설을 세 문장으로 써 주세요. 아래 근거 안에서만 작성하고 자료에 없는 내용은 만들지 마세요. 사실과 추측을 구분하고 확인이 필요한 점을 알려 주세요.\n자료: ${r.name}\n확인한 내용: ${r.fact}\n출처: ${r.source}\n${r.url}`);}if(action==='copy-prompt'){try{await navigator.clipboard.writeText($('#prompt-text').value);toast('복사했어요. 선생님과 사용하는 AI에 붙여 넣으세요.');}catch{$('#prompt-text').select();toast('요청문을 선택했어요. 기기의 복사 기능을 사용하세요.');}}});
$('#import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>1500000)throw Error('작업 파일이 너무 큽니다.');const next=validateProject(JSON.parse(await file.text()));if(confirm('현재 기기의 기록을 가져온 작업으로 바꿀까요? 현재 기록은 먼저 내려받아 보관하세요.')){project=next;compareIds=(project.answers['compare-selected']||'').split(',').filter(id=>artifacts.some(a=>a.id===id)).slice(0,2);migrateComparisonNotes();save();$('#modal')?.close();render();toast('작업을 가져왔어요. 이어서 활동하세요.');}}catch(error){toast('가져오지 못했어요. '+error.message);}event.target.value='';});
window.addEventListener('hashchange',()=>{slide=0;reveal=false;render();window.scrollTo(0,0);});
document.addEventListener('keydown',event=>{if($('#modal')?.open||event.target.closest('input,textarea,select,button,a')||!location.hash.startsWith('#lesson/'))return;if(event.key==='ArrowRight'&&slide<5){slide++;reveal=false;render();}if(event.key==='ArrowLeft'&&slide>0){slide--;reveal=false;render();}});
render();
