import {escapeHtml as e} from './model.js';
import {textbook} from './data.js';
import {lessonOneFigure,observationIds} from './lesson-one.js';
import {verificationSets} from './lesson-two-data.js';
export const secondSteps=['질문 이어가기','우리 질문 조사','추가 문장 살피기','문장 검증','함께 정리','조사 나누기'];
export const secondTimes=[5,12,4,12,4,3];
export const secondWorksheet='assets/worksheets/lesson-2.pdf';
export const worksheetFor=id=>observationIds.includes(id)?`assets/worksheets/lesson-2-${id}.pdf`:secondWorksheet;
const paper=(page,t)=>`<div class="l1-paper-note"><span>활동지 ${page}쪽</span><p>${t}</p></div>`;
const link=(url,label)=>`<a class="button quiet" href="${e(url)}" target="_blank" rel="noopener">${e(label)} ↗</a>`;
const statements=set=>`<ol class="l2-claims">${set.claims.map((c,i)=>`<li><span>문장 ${i+1}</span><p>${e(c.text)}</p></li>`).join('')}</ol>`;
const sources=set=>`<div class="l2-research-sources"><section><h2>교과서에서 찾기</h2><p>비상교육 사회 5-2 <strong>${set.page}쪽</strong>의 사진과 설명을 살펴봅니다.</p>${link(textbook.url,'교과서 열기')}</section><section><h2>공식 기관 자료에서 찾기</h2><p>${e(set.site)}</p><p>찾을 자료·검색어: <strong>${e(set.search)}</strong></p>${link(set.url,set.direct?'공식 설명 바로 열기':'공식 사이트 열기')}<p class="l1-note">${set.direct?'페이지의 46장 설명을 살펴봅니다.':'기관 첫 화면에서 검색 또는 소장품·전시 메뉴로 이동해 위 검색어로 찾습니다.'} 유물의 이름과 시대를 확인합니다.</p></section></div>`;
export function teacherForm(id='house'){
 const set=verificationSets[id]||verificationSets.house;
 return `<h2>교사용 정답·근거 · ${e(set.name)}</h2><p>먼저 학생이 1차시에 만든 질문을 조사하게 합니다. 질문의 답은 아래 문장 해설과 별개이며, 찾은 자료가 답을 뒷받침하는지 살펴봅니다. 답을 찾지 못한 질문은 3차시로 이어갑니다.</p><h3>추가 문장 해설</h3><p>학생이 근거와 최종 판단을 기록한 뒤 함께 살펴봅니다. 아래 판단은 제시된 자료를 기준으로 합니다.</p><ol class="l2-teacher-answers">${set.claims.map(c=>`<li><h3>${e(c.text)}</h3><p><b>${e(c.result)}</b> · ${e(c.reason)}</p>${c.fix?`<p>수정 예시: ${e(c.fix)}</p>`:''}</li>`).join('')}</ol><p>확인 자료: 비상교육 사회 5-2 ${set.page}쪽 / ${e(set.site)} · ${e(set.search)}</p>${link(textbook.url,'교과서 열기')}${link(set.url,set.direct?'공식 설명 열기':'공식 기관에서 자료 찾기')}<p class="l1-note">AI 설명 검증을 위한 학습용 문장입니다. 사실과 오류, 제시 자료로 확인할 수 없는 내용을 섞어 준비했습니다. 실시간 AI 답변이 아닙니다. 예상의 정오보다 출처와 근거가 최종 판단을 뒷받침하는지 살펴봅니다.</p>`;
}
export function lessonTwo({step,btn,source='house'}){
 const id=observationIds.includes(source)?source:'house',set=verificationSets[id];
 const titles=['지난 시간의 질문을 이어 볼까요?','우리 질문의 답을 찾아봅시다.','추가로 살펴볼 세 문장, 사실일까요?','자료를 찾아 문장을 확인해 봅시다.','알아낸 답과 확인한 문장을 정리해요.','우리 모둠은 이렇게 알아보았습니다.'];
 const leads=['1차시 활동지를 펴고, 우리가 고른 유물과 직접 만든 질문을 확인해 봅시다.','지난 시간에 정한 방법을 떠올리며 교과서와 공식 자료에서 답의 단서를 찾아봅시다.','우리 질문에 이어, 같은 유물에 대한 설명도 확인해 봅시다.','각 문장을 뒷받침하거나 바로잡을 근거를 찾아 최종 판단을 해 봅시다.','우리 질문의 답을 살펴보고, 거짓으로 확인한 설명도 사실에 맞게 고쳐 봅시다.','우리 질문에서 알아낸 내용 하나와 추가 문장을 검증한 과정 하나를 나누어 봅시다.'];
 const selector=`<div class="l2-source-tabs" role="group" aria-label="조사할 유물 선택">${observationIds.map(key=>btn(verificationSets[key].name,'l2-source',`data-id="${key}" aria-pressed="${key===id}"`,'quiet small')).join('')}</div>`;
 let body='';
 if(step===0)body=`<div class="l1-observe">${lessonOneFigure(id)}<div class="l1-observe-copy"><p class="l1-side-label">지난 시간에 고른 유물</p><h2>${e(set.name)}</h2><p>1차시 활동지 02에 적은 질문을 읽어 보세요.</p><ol class="l1-question-turns"><li>우리 질문의 답을 자료에서 찾아요.</li><li>추가 문장 3개도 같은 자료로 확인해요.</li><li>알아낸 내용과 남은 궁금증을 정리해요.</li></ol>${link(worksheetFor(id),'이 유물 활동지 받기 · 2쪽')}</div></div>${paper('1','‘우리의 질문’에 1차시에서 만든 질문을 그대로 옮겨 적어 봅시다.')}<p class="l1-note">다른 유물이 표시되면 위에서 바꿔 주세요. 종이 활동지의 질문을 이어서 사용합니다.</p>`;
 if(step===1)body=`<div class="l1-share-statement"><span>1차시에서 만든 우리의 질문</span><p>무엇이 궁금했나요? 어떤 내용을 찾으면 답할 수 있을까요?</p></div>${sources(set)}${paper('1','확인한 자료와 찾은 근거를 적고, 그 근거로 알 수 있는 답을 써 봅시다.')}<details class="l1-hint"><summary>찾기 어렵다면 이렇게 해 보세요.</summary><p>유물 이름에 질문 속 낱말을 더해 찾아보세요. 어려운 말이나 찾을 곳은 선생님께 물어봅니다.</p><p>답의 일부만 찾았다면 알게 된 부분을 적습니다. 나머지는 ‘더 알아볼 점’에 남겨 다음 시간에 이어서 조사합니다.</p></details>`;
 if(step===2)body=`${statements(set)}${paper('2','문장 1~3의 처음 생각에 사실 / 거짓 / 잘 모르겠음 중 하나를 표시해 봅시다.')}<p class="l1-note">이 문장들은 우리 질문에 더해 살펴볼 내용입니다. 생각이 다른 부분은 자료에서 함께 확인해 봅시다.</p>`;
 if(step===3)body=`${statements(set)}${sources(set)}<div class="l2-check-guide"><p><b>사실</b> 자료의 설명이 문장의 내용을 뒷받침합니다.</p><p><b>거짓</b> 자료에서 문장과 다른 사실을 확인했습니다.</p><p><b>판단하기 어려움</b> 살펴본 자료만으로 맞는지 틀린지 알 수 없습니다.</p></div>${paper('2','문장마다 ‘확인한 자료’와 ‘찾은 근거’를 쓰고, 최종 판단을 표시해 봅시다.')}<p class="l1-note">자료에는 교과서 쪽수 또는 기관 이름·자료 제목을 적습니다. 근거를 못 찾았다면 ‘이 자료에서는 확인할 수 없음’이라고 씁니다. 자료에 없다는 이유만으로 거짓이라고 판단하지 않습니다.</p>`;
 if(step===4)body=`<div class="l1-research-list"><section><span>01</span><div><h2>우리 질문의 답을 살펴봐요.</h2><p>활동지 1쪽의 답을 근거와 비교해 보세요. 아직 모르는 것은 ‘더 알아볼 점’으로 남깁니다.</p></div></section><section><span>02</span><div><h2>잘못된 문장을 바로잡아요.</h2><p>활동지 2쪽에서 거짓으로 확인한 문장 하나를 골라, 틀린 부분을 사실에 맞게 고쳐 씁니다.</p></div></section></div><p class="l1-note">‘판단하기 어려움’으로 남긴 내용은 사실처럼 고쳐 쓰지 않습니다.</p>`;
 if(step===5)body=`<div class="l1-share-statement"><span>우리 질문에서 알아낸 것</span><p>“우리는 …이 궁금했습니다. …에서 …을 알게 되었습니다.”</p></div><div class="l1-share-statement"><span>추가 문장을 확인한 과정</span><p>“문장 …번은 …이라고 판단했습니다. …에서 …을 확인했기 때문입니다.”</p></div><p class="l1-note">아직 답을 찾지 못한 질문은 어디까지 알아봤는지와 더 알아볼 점을 말합니다.</p><details class="l1-hint"><summary>검증을 마친 뒤 · 선생님과 해설 확인</summary>${teacherForm(id)}</details><div class="l1-next-lesson"><span>3차시 예고</span><p>같은 유물과 활동지 두 쪽을 가져옵니다. 우리 질문의 조사 기록과 문장 검증 기록을 함께 활용하고, 더 필요한 정보를 찾아 모둠 조사표를 만듭니다.</p></div>`;
 return `<div class="l1-workspace"><nav class="l1-progress" aria-label="2차시 활동 순서"><ol>${secondSteps.map((n,i)=>`<li>${btn(`<span>0${i+1}</span>${n}`,'l2-step',`data-step="${i}" ${i===step?'aria-current="step"':''}`)}</li>`).join('')}</ol></nav><article class="l1-content"><header class="l1-page-heading"><p class="l1-kicker">2차시 · LOOK <span>${secondSteps[step]} · ${secondTimes[step]}분</span></p><h1>${titles[step]}</h1><p class="l1-lead">${leads[step]}</p></header>${selector}${step===2||step===3?'<p class="l2-example-label">AI 설명 검증을 위한 학습용 문장 · 오류가 포함되어 있습니다.</p>':''}${body}<nav class="l1-nav" aria-label="2차시 활동 이동">${btn('← 이전','l2-step',`data-step="${step-1}" ${step===0?'disabled':''}`,'quiet')}<span>${step+1} / 6</span>${step<5?btn('다음 →','l2-step',`data-step="${step+1}"`,'primary'):'<a class="button primary" href="#lesson/3">3차시로 →</a>'}</nav></article></div>`;
}
