import {escapeHtml as e} from './model.js';
import {textbook} from './data.js';
export const firstSteps=['그림과 만나기','단서 찾기','사실과 추측','질문 만들기','AI와 탐구하기','오늘의 발견'];
const times=[5,7,8,8,6,6];
const prompts=[
 {text:'어떤 사람은 다른 사람보다 크게 그려져 있다.',correct:'직접 보임',why:'그림 속 인물의 크기는 눈으로 비교할 수 있어요.'},
 {text:'크게 그려진 사람은 중요한 사람이었을 것이다.',correct:'추측',why:'크기 차이를 근거로 생각한 해석이에요. 교과서 설명과 다른 자료로 확인해야 해요.'},
 {text:'그림 속 사람들이 먹은 점심 메뉴는 쌀밥이었다.',correct:'알 수 없음',why:'이 장면에는 식사 모습이 없어요. 음식과 관련된 다른 자료가 필요해요.'}
];
const clues=[['크기','앞뒤 사람의 몸 크기를 비교해 보세요.'],['옷차림','옷의 길이, 색과 무늬를 살펴보세요.'],['행동','손에 든 물건과 몸의 자세를 살펴보세요.']];
const tasks=[['정리','우리가 쓴 관찰 내용을 표로 정리하기','좋아요. AI가 새 내용을 덧붙이지 않았는지 원래 기록과 비교해요.'],['질문','궁금한 점을 조사할 질문으로 다듬기','좋아요. 어떤 그림의 어느 부분을 보고 생긴 질문인지 함께 알려 줘요.'],['상상','벽화에 안 보이는 일을 사실처럼 채우기','다시 생각해요. 상상한 이야기는 역사적 사실의 근거가 될 수 없어요.'],['판정','AI의 답만 보고 역사적 사실로 결정하기','다시 생각해요. 교과서나 박물관 자료와 비교해서 확인해야 해요.']];
function image(markers=false,active='') {return `<figure class="l1-figure"><div class="l1-image"><img src="assets/images/visang-susan-lesson1.jpg" alt="수산리 고분 벽화의 인물 부분. 크기가 다른 인물들이 긴 옷을 입고 서 있으며 일부는 큰 가리개를 들고 있습니다.">${markers?clues.map(([name],i)=>`<button class="l1-pin pin-${i} ${active===name?'selected':''}" data-action="l1-clue" data-clue="${name}" aria-label="${name} 관찰하기" aria-pressed="${active===name}">${i+1}</button>`).join(''):''}</div><figcaption>수산리 고분 벽화 · 인물 부분 발췌 <a href="${textbook.url}" target="_blank" rel="noopener">비상교육 사회 5-2(설규주), 26쪽 ↗</a></figcaption></figure>`;}
export function lessonOne({step,answer,field,btn}){
 const active=answer('l1-clue')||'크기';let content='';
 if(step===0)content=`<p class="l1-kicker">오늘의 탐구 · 5분</p><h1>그림 한 장으로 옛사람의 생활을 알 수 있을까?</h1><p class="l1-lead">말없이 30초 동안 그림을 살펴보세요. 가장 먼저 눈에 들어온 것을 짝에게 말해 봅시다.</p>${image()}<div class="l1-bottom"><p><b>오늘 할 일</b><br>그림에서 단서를 찾고, 더 알아보고 싶은 질문을 만듭니다.</p><p><b>오늘 남길 것</b><br>관찰한 내용 · 근거를 붙인 생각 · 탐구 질문</p></div>`;
 if(step===1)content=`<p class="l1-kicker">관찰 · 7분</p><h1>작은 차이도 단서가 돼요.</h1><p class="l1-lead">그림의 번호를 누르고 살펴보세요. 아직 인물의 신분이나 이름을 맞힐 필요는 없어요.</p>${image(true,active)}<div class="l1-clue-tabs">${clues.map(([name],i)=>btn(`${i+1}. ${name}`,'l1-clue',`data-clue="${name}" aria-pressed="${active===name}"`,active===name?'primary':'quiet')).join('')}</div><div class="l1-prompt"><b>${active} 관찰</b><p>${clues.find(c=>c[0]===active)[1]}</p></div>${field('l1-note-'+active,'이 부분에서 직접 본 것','이름을 몰라도 괜찮아요. 모양·색·크기·위치를 말로 적어 보세요.',2)}<details class="l1-hint"><summary>말문이 막히면?</summary><p>“왼쪽 사람은 …”, “두 사람의 옷은 …”, “손에 …을 들고 있다”처럼 시작해 보세요.</p></details>`;
 if(step===2)content=`<p class="l1-kicker">근거 구분 · 8분</p><h1>보이는 것과 생각한 것은 달라요.</h1><p class="l1-lead">각 문장이 어디에 해당하는지 골라 보세요. 짝과 다르면 그림을 근거로 설명해 봅시다.</p>${image()}<div class="l1-quiz">${prompts.map((p,i)=>{const choice=answer('l1-quiz-'+i);return `<section><span>0${i+1}</span><div><h2>${p.text}</h2><div class="l1-choices">${['직접 보임','추측','알 수 없음'].map(c=>btn(c,'l1-quiz',`data-index="${i}" data-choice="${c}" aria-pressed="${choice===c}"`,choice===c?'primary':'quiet')).join('')}</div>${choice?`<p class="l1-feedback" role="status"><b>${choice===p.correct?'맞아요.':'다시 살펴봐요. '+p.correct+'에 해당해요.'}</b> ${p.why}</p>`:''}</div></section>`;}).join('')}</div><details class="l1-hint"><summary>생각을 말한 뒤 교과서 해설 확인하기</summary><p>교과서는 귀족 부부와 그 뒤를 따르는 사람들, 재주를 부리는 사람들이 그려진 장면으로 설명해요. 크게 그렸다고 실제 키가 더 컸다고 단정할 수는 없어요.</p></details>`;
 if(step===3)content=`<p class="l1-kicker">모둠 질문 · 8분</p><h1>“왜?” 앞에 내가 본 것을 붙여요.</h1><p class="l1-lead">각자 궁금한 점을 말하고, 우리 모둠이 더 알아보고 싶은 질문 하나를 고릅니다.</p>${image()}<div class="l1-example"><small>질문을 만드는 방법</small><p>사람들의 크기가 다르게 그려져 있다.<br>→ 왜 어떤 사람을 더 크게 그렸을까?</p></div><div class="l1-writing">${field('observed','① 그림에서 직접 본 것 두 가지','앞에서 기록한 크기·옷차림·행동 중 골라 적어요.',2)}${field('inference','② 그 단서에서 생각한 생활 모습과 까닭','…을 보니 …했을 것 같다. 왜냐하면 …',2)}${field('curious','③ 우리 모둠이 더 알아보고 싶은 질문','관찰한 단서가 들어가도록 질문해 보세요.',2)}</div>`;
 if(step===4)content=`<p class="l1-kicker">AI의 역할 예상 · 6분</p><h1>AI에게 어떤 도움을 받을까요?</h1><p class="l1-lead">다음 시간에는 AI의 답을 비교할 거예요. 오늘은 AI에게 맡길 일과 우리가 확인할 일을 생각해 봅시다.</p><div class="l1-ai-tasks">${tasks.map(([id,title,why])=>`<section>${btn(title,'l1-ai',`data-task="${id}" aria-expanded="${answer('l1-ai-'+id)==='yes'}"`,'quiet')}${answer('l1-ai-'+id)==='yes'?`<p role="status">${why}</p>`:''}</section>`).join('')}</div>${field('ai-help','우리 질문을 탐구할 때 AI에게 부탁하고 싶은 일','무엇을 도와 달라고 할지 구체적으로 적어요.',2)}${field('l1-human-check','AI의 답을 확인하려면 우리가 할 일','어떤 자료를 찾아 무엇과 비교할까요?',2)}<p class="l1-note">이 활동은 AI의 역할을 생각해 보는 활동이에요. 위 설명은 수업용으로 작성했으며 실시간 AI 답변이 아닙니다.</p>`;
 if(step===5){const filled=['observed','inference','curious','ai-help'].filter(k=>answer(k).trim()).length;content=`<p class="l1-kicker">공유와 정리 · 6분</p><h1>우리 모둠의 첫 발견</h1><p class="l1-lead">한 모둠씩 “우리는 ___을 보고, ___이 궁금해졌어요.”라고 소개해 봅시다.</p><div class="l1-summary">${[['observed','직접 본 것'],['inference','근거를 붙인 생각'],['curious','더 알아볼 질문'],['ai-help','AI에게 부탁할 일'],['l1-human-check','우리가 확인할 일']].map(([key,label])=>`<section><h2>${label}</h2><p>${e(answer(key)||'아직 적지 않았어요. 앞 단계에서 기록해 보세요.')}</p></section>`).join('')}</div><p class="l1-note">핵심 기록 ${filled}/4개 작성 · 기록은 이 기기에 자동 저장돼요.</p><div class="l1-bottom"><p><b>다음 시간</b><br>우리 질문에 대한 AI의 답을 비교하고 교과서로 확인해요.</p>${btn('우리 기록 인쇄','report','','quiet')}</div>`;}
 return `<div class="l1-layout"><aside class="l1-rail"><a href="#home">← 수업 목차</a><p>AI-L.E.A.P</p><strong>01 <small>LOOK</small></strong><h2>벽화에서<br>생활 찾기</h2><ol>${firstSteps.map((s,i)=>`<li>${btn(`<span>${i+1}</span>${s}<small>${times[i]}분</small>`,'l1-step',`data-step="${i}" ${i===step?'aria-current="step"':''}`)}</li>`).join('')}</ol><p>비상 사회 5-2 · 26쪽<br>5학년 / 40분 수업</p>${btn('교사 안내','guide','data-id="1"','quiet small')}</aside><article class="l1-content">${content}<nav class="l1-nav" aria-label="1차시 활동 이동">${btn('← 이전','l1-step',`data-step="${step-1}" ${step===0?'disabled':''}`,'quiet')}<span>${step+1} / 6</span>${step<5?btn('다음 →','l1-step',`data-step="${step+1}"`,'primary'):'<a class="button primary" href="#lesson/2">2차시로 →</a>'}</nav></article></div>`;
}
