import {escapeHtml as e} from './model.js';
import {artifacts,textbook} from './data.js';
export const firstSteps=['여섯 자료 만나기','자세히 관찰하기','궁금한 점 모으기','우리 모둠의 질문','AI가 도울 일','발견 나누기'];
const times=[6,8,8,8,6,4];
export const observationIds=['susan','spoon','house','figurines','armor','pagoda'];
const notes={
 susan:{topic:'옷차림과 신분',look:['사람의 크기','옷의 무늬','손에 든 물건'],question:'왜 어떤 사람을 더 크게 그렸을까?',limit:'그림 속 크기가 실제 키와 같을까요?',notice:'벽화의 인물 부분을 발췌했어요.'},
 spoon:{topic:'음식과 식기',look:['수저의 모양','사발의 깊이','오늘날 식기와 차이'],question:'이 그릇에는 어떤 음식을 담았을까?',limit:'그릇의 모양만으로 먹었던 음식을 알 수 있을까요?'},
 house:{topic:'집과 건물',look:['지붕의 모양','아래쪽 기둥','바닥의 높이'],question:'왜 집의 바닥을 높게 만들었을까?',limit:'집을 본뜬 물건 하나로 모든 집의 모습을 알 수 있을까요?',notice:'사람이 사는 집이 아니라 집 모양으로 만든 토기예요.'},
 figurines:{topic:'사람의 모습',look:['팔과 다리의 자세','옷의 모양','두 인물의 차이'],question:'왜 사람의 모습을 흙으로 작게 만들었을까?',limit:'작은 인물의 자세만 보고 무엇을 하는지 알 수 있을까요?'},
 armor:{topic:'철을 다루는 기술',look:['머리를 덮는 부분','몸을 감싸는 부분','이어 붙인 부분'],question:'갑옷을 입고 어떻게 움직였을까?',limit:'사진만 보고 갑옷의 무게나 움직임을 알 수 있을까요?'},
 pagoda:{topic:'건축과 불교문화',look:['층마다 있는 지붕','아래쪽 기둥','위아래 크기 차이'],question:'사람들은 왜 큰 탑을 세웠을까?',limit:'겉모양만 보고 탑을 세운 까닭을 알 수 있을까요?',notice:'교과서에 실린 석탑 복원 모습이에요. 당시 모습을 그대로 찍은 사진은 아니에요.'}
};
const get=id=>artifacts.find(a=>a.id===id);
export const observationKey=(id,kind)=>`l1-${id}-${kind}`;
const chosen=(answer,key)=>observationIds.includes(answer(key))?answer(key):'susan';
export function lessonOneFigure(id,small=false){const a=get(id);return `<figure class="l1-figure ${small?'l1-small':''}"><div class="l1-image"><img src="assets/images/${e(a.image)}" alt="${e(a.name)} · 비상 교과서 ${a.page}쪽${id==='pagoda'?' · 복원 모습':''}"></div><figcaption><span>${e(a.name)}${id==='pagoda'?' · 복원 모습':''}</span><a href="${textbook.url}" target="_blank" rel="noopener">비상 사회 5-2 · ${a.page}쪽 ↗</a></figcaption></figure>`;}
function selector(active,btn){return `<div class="l1-object-tabs" role="group" aria-label="관찰 자료 선택">${observationIds.map((id,i)=>btn(`${i+1}. ${get(id).name}`,'l1-object',`data-id="${id}" aria-pressed="${active===id}"`,active===id?'primary':'quiet')).join('')}</div>`;}
export function lessonOneReport(answer){const id=chosen(answer,'l1-focus');return `<p><b>모둠이 고른 자료:</b> ${e(get(id).name)}</p>${observationIds.map(a=>{const seen=answer(observationKey(a,'observed')),q=answer(observationKey(a,'question'));return seen||q?`<h4>${e(get(a).name)}</h4>${seen?`<p>직접 본 것: ${e(seen)}</p>`:''}${q?`<p>궁금한 점: ${e(q)}</p>`:''}`:'';}).join('')}${[['curious','모둠 질문'],['ai-help','AI에게 부탁할 일'],['l1-human-check','우리가 확인할 일']].map(([k,label])=>answer(k)?`<p><b>${label}:</b> ${e(answer(k))}</p>`:'').join('')}`;}
export function lessonOne({step,answer,field,btn}){
 const id=chosen(answer,'l1-selected'),a=get(id),n=notes[id],focus=chosen(answer,'l1-focus'),f=get(focus);let content='';
 if(step===0)content=`<p class="l1-kicker">자료 둘러보기 · 6분</p><h1>옛사람들은 어떻게 살았을까요?</h1><p class="l1-lead">여섯 자료를 둘러보세요. 가장 궁금한 자료 하나를 고르고, 눈에 들어온 부분을 짝에게 말해 봅시다.</p><div class="l1-gallery">${observationIds.map((key,i)=>{const x=get(key);return `<section><button class="l1-gallery-image" data-action="l1-open" data-id="${key}" aria-label="${e(x.name)} 자세히 관찰하기"><img src="assets/images/${e(x.image)}" alt="${e(x.name)}${key==='pagoda'?' 복원 모습':''}"></button><p><span>0${i+1} / ${x.nation}</span><strong>${x.name}</strong><small>${notes[key].topic}${key==='pagoda'?' · 복원 모습':''} · ${x.page}쪽</small></p></section>`;}).join('')}</div><p class="l1-note">사진 출처: 비상교육 사회 5-2(설규주), 25·26·28·30쪽. 사진을 누르면 크게 볼 수 있어요.</p>`;
 if(step===1)content=`<p class="l1-kicker">모둠 관찰 · 8분</p><h1>어느 부분이 눈에 들어왔나요?</h1><p class="l1-lead">한 자료를 골라 모양·크기·자세를 살펴보세요. 짝에게 사진의 어느 부분을 봤는지 짚어 주세요.</p>${selector(id,btn)}${lessonOneFigure(id)}<div class="l1-clue-list">${n.look.map((s,i)=>`<span>${i+1}. ${s}</span>`).join('')}</div>${n.notice?`<p class="l1-note">${n.notice}</p>`:''}${field(observationKey(id,'observed'),'우리 눈으로 찾은 것','사진에서 보이는 부분을 구체적으로 적어요.',2)}<details class="l1-hint"><summary>말문이 막히면?</summary><p>“위쪽에는 …이 있다.” “두 부분의 모양이 …하다.” “지금 쓰는 물건과 …이 다르다.”처럼 말해 보세요.</p></details>`;
 if(step===2)content=`<p class="l1-kicker">궁금증 발견 · 8분</p><h1>사진만 보고 알 수 있을까요?</h1><p class="l1-lead">직접 본 것에서 궁금한 점을 떠올려 보세요. 다른 자료를 골라 질문을 더 남겨도 좋아요.</p>${selector(id,btn)}<div class="l1-question-work">${lessonOneFigure(id)}<div><div class="l1-prompt"><b>우리가 직접 본 것</b><p>${e(answer(observationKey(id,'observed'))||'앞 단계에서 발견한 부분을 함께 말해 보세요.')}</p></div><p class="l1-open-question">${n.limit}</p>${field(observationKey(id,'question'),'이 자료에서 더 알아보고 싶은 점','누가 / 언제 / 어떻게 / 왜 …?',3)}<details class="l1-hint"><summary>질문 예시 보기</summary><p>${n.question}</p></details></div></div>`;
 if(step===3)content=`<p class="l1-kicker">모둠 대화 · 8분</p><h1>함께 알아보고 싶은 것은?</h1><p class="l1-lead">모은 질문을 돌아가며 읽어 주세요. 가장 알아보고 싶은 질문을 고르고, 궁금한 까닭을 이야기해 봅시다.</p><div class="l1-question-list">${observationIds.map(key=>{const q=answer(observationKey(key,'question'));return `<section><img src="assets/images/${e(get(key).image)}" alt="${e(get(key).name)}"><div><small>${get(key).name}</small><p>${e(q||'이 자료에는 아직 질문이 없어요.')}</p></div>${btn(q?'이 질문 고르기':'질문 적으러 가기',q?'l1-focus':'l1-question',`data-id="${key}" ${q?`aria-pressed="${focus===key}"`:''}`,'quiet small')}</section>`;}).join('')}</div><div class="l1-prompt"><b>우리 모둠이 고른 자료: ${f.name}</b></div>${field('curious','우리 모둠의 질문','모둠 친구들의 생각을 모아 적어요.',2)}<p class="l1-note">오늘은 질문을 모아요. 다음 시간에 AI의 답과 역사 자료를 비교하며 질문을 다듬습니다.</p>`;
 if(step===4){const helps=[['organize','우리 관찰 메모 정리하기','사진에서 본 내용을 빠뜨리지 않고 묶어 줄 수 있을까?'],['words','어려운 낱말 뜻 알아보기','토우·청동·석탑 같은 말을 쉽게 설명해 줄 수 있을까?'],['questions','질문할 거리 더 떠올리기','우리 질문과 연결되는 다른 궁금증을 제안해 줄 수 있을까?']];content=`<p class="l1-kicker">AI의 역할 예상 · 6분</p><h1>AI가 우리 탐구를 어떻게 도울까요?</h1><div class="l1-prompt"><b>우리 모둠의 질문</b><p>${e(answer('curious')||'먼저 우리 모둠의 질문을 정해 보세요.')}</p></div><p class="l1-lead">어떤 도움을 받고 싶은지 골라 이야기해 보세요.</p><div class="l1-help-options">${helps.map(([key,title,sub])=>`<section>${btn(title,'l1-help',`data-help="${key}" data-value="${title}" aria-pressed="${answer('l1-help-choice')===key}"`,answer('l1-help-choice')===key?'primary':'quiet')}<p>${sub}</p></section>`).join('')}</div>${field('ai-help','우리 모둠이 AI에게 부탁할 일','직접 다른 부탁을 적어도 좋아요.',2)}<div class="l1-limit"><h2>AI도 잘못 설명할 수 있어요.</h2><p>그림에 없는 내용을 만들어 말할 수도 있어요. AI의 답을 무엇과 비교하면 좋을까요?</p></div>${field('l1-human-check','우리가 찾아보거나 확인할 자료','교과서, 박물관 설명, 다른 유물 사진 …',2)}<p class="l1-note">오늘은 AI가 도울 일을 예상합니다. 실제 AI에게 질문하고 답을 확인하는 활동은 2차시에 해요.</p>`;}
 if(step===5)content=`<p class="l1-kicker">공유 · 4분</p><h1>우리는 이것이 궁금해졌어요.</h1><p class="l1-lead">“우리는 ___을 보고, ___이 궁금해졌어요.” 모둠의 질문을 친구들에게 소개해 주세요.</p><div class="l1-share">${lessonOneFigure(focus,true)}<div class="l1-summary">${[[f.name,answer(observationKey(focus,'observed'))],['우리 모둠의 질문',answer('curious')],['AI에게 부탁할 일',answer('ai-help')],['우리가 확인할 자료',answer('l1-human-check')]].map(([label,value])=>`<section><h2>${e(label)}</h2><p>${e(value||'앞 단계에서 이야기를 나누고 기록해 보세요.')}</p></section>`).join('')}</div></div><div class="l1-bottom"><p><b>다음 시간</b> 우리 질문을 AI에게 묻고 답을 자료와 비교해요.</p>${btn('1차시 기록 인쇄','l1-report','','quiet')}</div>`;
 return `<div class="l1-layout"><aside class="l1-rail"><a href="#home">← 수업 목차</a><p>AI-L.E.A.P</p><strong>01 <small>LOOK</small></strong><h2>삼국과 가야의 궁금증 찾기</h2><ol>${firstSteps.map((s,i)=>`<li>${btn(`<span>${i+1}</span>${s}<small>${times[i]}분</small>`,'l1-step',`data-step="${i}" ${i===step?'aria-current="step"':''}`)}</li>`).join('')}</ol><p>비상 사회 5-2<br>5학년 / 40분 수업</p>${btn('교사 안내','guide','data-id="1"','quiet small')}${btn('활동지','worksheet','data-id="1"','quiet small')}</aside><article class="l1-content">${content}<nav class="l1-nav" aria-label="1차시 활동 이동">${btn('← 이전','l1-step',`data-step="${step-1}" ${step===0?'disabled':''}`,'quiet')}<span>${step+1} / 6</span>${step<5?btn('다음 →','l1-step',`data-step="${step+1}"`,'primary'):'<a class="button primary" href="#lesson/2">2차시로 →</a>'}</nav></article></div>`;
}
