export const STORAGE_KEY='moakit-5class-v1';
export const fresh=()=>({version:1,school:'',group:'',answers:{},records:[],relations:[],exhibit:[],checked:[]});
export const escapeHtml=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
const string=(v,max=12000)=>{if(typeof v!=='string'||v.length>max)throw Error('글자 수 또는 자료 형식이 맞지 않습니다.');return v;};
const texts=(v,max=500)=>{if(!v||Array.isArray(v)||typeof v!=='object'||Object.keys(v).length>max)throw Error('기록 형식이 맞지 않습니다.');const out={};for(const [k,x]of Object.entries(v)){if(!/^[a-zA-Z0-9_-]{1,100}$/.test(k)||['__proto__','constructor','prototype'].includes(k))throw Error('기록 항목이 올바르지 않습니다.');out[k]=string(x);}return out;};
export function validateProject(p){if(!p||p.version!==1)throw Error('5class 작업 파일이 아닙니다.');const out=fresh();out.school=string(p.school,100);out.group=string(p.group,100);out.answers=texts(p.answers);if(!Array.isArray(p.records)||p.records.length>40)throw Error('자료는 40개까지 사용할 수 있습니다.');out.records=p.records.map(r=>{const t={};for(const k of ['id','name','nation','period','kind','material','fact','source','url','base'])t[k]=string(r[k]??'',k==='fact'?12000:1000);if(!/^[a-zA-Z0-9_-]{1,60}$/.test(t.id)||!t.name||!safeUrl(t.url))throw Error('자료 이름이나 출처 주소를 확인해 주세요.');return t;});if(new Set(out.records.map(r=>r.id)).size!==out.records.length)throw Error('중복된 자료가 있습니다.');if(!Array.isArray(p.relations)||p.relations.length>50)throw Error('관계도 형식을 확인해 주세요.');out.relations=p.relations.map(r=>{const t={};for(const k of ['id','from','to','label','status','source'])t[k]=string(r[k]??'',1000);if(!t.from||!t.to||!t.label)throw Error('관계도 내용을 확인해 주세요.');return t;});for(const key of ['exhibit','checked']){if(!Array.isArray(p[key])||p[key].length>40||p[key].some(x=>typeof x!=='string'||!out.records.some(r=>r.id===x)))throw Error('전시 자료가 조사표와 맞지 않습니다.');out[key]=[...new Set(p[key])];}return out;}
export function wordCounts(text,keywords){return [...new Set(keywords.split(/[,，\n]/).map(x=>x.trim()).filter(x=>x.length>0&&x.length<30))].slice(0,20).map(word=>({word,count:text.split(word).length-1})).sort((a,b)=>b.count-a.count||a.word.localeCompare(b.word,'ko'));}
export function selectedRecords(project){return project.exhibit.map(id=>project.records.find(r=>r.id===id)).filter(Boolean);}
export function readiness(project){return selectedRecords(project).map(r=>({id:r.id,name:r.name,ready:!!project.answers['final-'+r.id]?.trim()&&project.checked.includes(r.id)&&!!safeUrl(r.url)}));}
