import test from 'node:test';import assert from 'node:assert/strict';import {fresh,validateProject,safeUrl,escapeHtml,wordCounts,selectedRecords,readiness} from '../model.js';import {artifacts,coreArtifacts,lessons,lessonVisuals}from '../data.js';
const record=()=>({id:'star',base:'star',name:'첨성대',nation:'신라',period:'7세기',kind:'건축물',material:'돌',fact:'돌로 쌓은 건물이다.',source:'국가유산포털',url:'https://www.heritage.go.kr/'});
test('10 lessons preserve LEAP progression and six individually authored pages',()=>{assert.equal(lessons.length,10);assert.deepEqual(lessons.map(x=>x.stage),['Look','Look','Explore','Explore','Explore','Act','Act','Act','Practice','Practice']);for(const l of lessons){assert.equal(l.pages.length,6);assert.ok(artifacts.find(a=>a.id===l.image));assert.ok(l.pages.every(p=>p.length===4&&p.every(Boolean)));}});
test('project round trip keeps research, analysis, order, draft and final',()=>{const p=fresh();p.records=[record()];p.exhibit=['star'];p.answers={'class-star':'건축','draft-star':'초안','final-star':'최종 해설',keywords:'돌','word-meaning':'해석'};p.checked=['star'];p.relations=[{id:'r1',from:'첨성대',to:'신라',label:'신라의 건축물',status:'확인한 사실',source:'star'}];assert.deepEqual(validateProject(JSON.parse(JSON.stringify(p))),p);assert.equal(selectedRecords(p)[0].id,'star');assert.equal(readiness(p)[0].ready,true);p.checked=[];assert.equal(readiness(p)[0].ready,false);});
test('reject broken files and malicious URLs without accepting partial state',()=>{assert.throws(()=>validateProject({version:2}));const p=fresh();p.records=[record()];p.exhibit=['unknown'];assert.throws(()=>validateProject(p));p.exhibit=[];p.records[0].url='javascript:alert(1)';assert.throws(()=>validateProject(p));for(const u of ['javascript:alert(1)','data:text/html,x','https://user:pass@example.com/','http://example.com'])assert.equal(safeUrl(u),'');assert.equal(safeUrl('https://example.com/'),'https://example.com/');});
test('escape student writing for displayed and exported HTML',()=>assert.equal(escapeHtml('<script>"&\'</script>'),'&lt;script&gt;&quot;&amp;&#39;&lt;/script&gt;'));
test('counts actual substrings, de-duplicates and retains zero counts',()=>assert.deepEqual(wordCounts('금관과 금동, 무덤과 무덤','금,무덤,금,돌'),[{word:'금',count:2},{word:'무덤',count:2},{word:'돌',count:0}]));

test('textbook links cover four countries and lesson visuals resolve without removing saved legacy IDs',()=>{assert.deepEqual([...new Set(coreArtifacts.map(a=>a.nation))].sort(),['가야','고구려','백제','신라']);assert.equal(new Set(artifacts.map(a=>a.id)).size,artifacts.length);for(const a of coreArtifacts){assert.ok(a.page>=25&&a.page<=31);assert.ok(safeUrl(a.url));}for(const ids of Object.values(lessonVisuals)){assert.equal(ids.length,6);for(const id of ids)assert.ok(artifacts.some(a=>a.id===id));}for(const id of ['mural','burner','tomb','crown','star'])assert.ok(artifacts.some(a=>a.id===id));});
test('full class work retains comparison and observation choices on import',()=>{const p=fresh();p.answers={'observation-artifact':'kitchen','compare-selected':'house,spoon','compare-evidence':'집과 음식 생활'};for(let i=0;i<40;i++){p.records.push({...record(),id:'r-'+i});for(const prefix of ['class-','ai-class-','draft-','final-','change-','guess-','method-'])p.answers[prefix+'r-'+i]='기록';}assert.deepEqual(validateProject(JSON.parse(JSON.stringify(p))),p);});
